/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.modules.reserves.wizard;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import org.iesapp.clients.iesdigital.reserves.BeanReserves;
import org.iesapp.modules.reserves.ReservesModule;
import org.iesapp.util.StringUtils;

/**
 *
 * @author Josep
 */
public class ReservesStep1 extends javax.swing.JPanel {
    private final DefaultListModel listmodel;

    /**
     * Creates new form StartupStep1
     */
    public ReservesStep1() {
        initComponents();
        listmodel = new DefaultListModel();
        jList1.setModel(listmodel);
        ButtonGroup group1 = new ButtonGroup();
        group1.add(jRadioButton1);
        group1.add(jRadioButton2);
        fillList();
        
        ActionListener chooseTypeListener = new ActionListener()
        {

            public void actionPerformed(ActionEvent e) {
                fillList();
            }
            
        };
        
        jRadioButton1.addActionListener(chooseTypeListener);
        jRadioButton2.addActionListener(chooseTypeListener);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        jRadioButton1.setSelected(true);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/iesapp/modules/reserves/ReservesBundle"); // NOI18N
        jRadioButton1.setText(bundle.getString("aules")); // NOI18N

        jRadioButton2.setText(bundle.getString("material")); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addGap(0, 304, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
       int sel = jList1.getSelectedIndex();
       ReservesWiz.getWizard().setNextFinishButtonEnabled(sel>=0);
       if(sel>=0)
       {
            if(jRadioButton1.isSelected())
            {
                ReservesWiz.wizardMap.put("type",BeanReserves.AULES+"");
                ReservesWiz.wizardMap.put("idRecurs", ReservesModule.listEspais.get(sel).getAula());
              
                String nomAula = StringUtils.noNull(ReservesModule.listEspais.get(sel).getAula())+" "+
                                 StringUtils.noNull(ReservesModule.listEspais.get(sel).getDescripcio());
                ReservesWiz.getWizard().setTitle(ReservesWiz.bundle.getString("nova")+" : "+ nomAula);
                ReservesWiz.wizardMap.put("nomRecurs", nomAula);
            }
            else
            {
                ReservesWiz.wizardMap.put("type",BeanReserves.MATERIAL+"");
                ReservesWiz.wizardMap.put("idRecurs",ReservesModule.listMaterials.get(sel).getId()+"");  
                String nomMaterial = StringUtils.noNull(ReservesModule.listMaterials.get(sel).getMaterial())+" "+
                                     StringUtils.noNull(ReservesModule.listMaterials.get(sel).getDescripcio())+" "+
                                     StringUtils.noNull(ReservesModule.listMaterials.get(sel).getUbicacio());
                        
                ReservesWiz.getWizard().setTitle(ReservesWiz.bundle.getString("nova")+" : "+nomMaterial);
                ReservesWiz.wizardMap.put("nomRecurs", nomMaterial); 
            }
       }
      
    }//GEN-LAST:event_jList1ValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void fillList() {
        listmodel.clear();
                if(jRadioButton1.isSelected())
                {
                    for(int i=0; i<ReservesModule.listEspais.size(); i++)
                    {
                        String s = StringUtils.noNull( ReservesModule.listEspais.get(i).getAula() ) +" " +
                                   StringUtils.noNull( ReservesModule.listEspais.get(i).getDescripcio() );
                        ReservesStep1.this.listmodel.addElement(s);
                    }
                }
                else
                {
                    for(int i=0; i<ReservesModule.listMaterials.size(); i++)
                    {
                        String s = StringUtils.noNull(ReservesModule.listMaterials.get(i).getMaterial())+" "+
                                   StringUtils.noNull(ReservesModule.listMaterials.get(i).getDescripcio())+" "+
                                   StringUtils.noNull(ReservesModule.listMaterials.get(i).getUbicacio());
                        ReservesStep1.this.listmodel.addElement(s);
                    }
                }
    }

    void refreshUI() {
        //
    }

    public boolean isValidated() {
         int sel = jList1.getSelectedIndex();
         return sel>=0;
    }

 
}
